### ISSUE TITLE
Changing endpoint when deploying?

### ISSUE THREAD

**Issue by tobiasger** [alexmacarthur/wp-vue#13]
This might be another topic that has nothing to do with this project per se. Sorry if that's the case.

I was wondering if there's an easy way to change the endpoint when deploying the site to Netlify? In my local environment I'm using an endpoint that's also running locally through MAMP. So I thought that it would be very handy if you somehow could tell Netlify to change the endpoint upon building/deploying the site, in that case to another endpoint that I'm hosting on another server. 

That would really make things easier for me at the start so that the production and development environment are connecting to different endpoints. Or is that a bad idea?

**Comment by alexmacarthur** [comment]
Great callout! I just made a change that loads values like the REST endpoint from environment variables. So, locally, you can use a `.env` or `.env.local` file for holding these values, and when you deploy to Netlify, you can define them in the dashboard. 

More on that here: https://github.com/alexmacarthur/wp-vue#set-your-environment-variables

Hope that helps!
