### ISSUE TITLE
Erro ENV_NODE

### ISSUE THREAD

**Issue by kleidsonfriend** [alexmacarthur/wp-vue#14]
Estava com problema ao rodar o comando "npm run serve", aparecia um erro sobre ENV_NODE. Resolvi esse problema retirando "ENV_NODE=development" e "ENV_NODE=production" das linhas 6 e 7, respectivamente do arquivo: package.json.

**Comment by alexmacarthur** [comment]
Gracias por informarme de esto! No estoy seguro de por qué estabas viendo esos problemas en particular, pero tienes razón. No es necesario definir esos valores ya que estoy usando `vue-cli`. Los he eliminado en la última versión:

https://github.com/alexmacarthur/wp-vue/releases/tag/v1.1.0
