### ISSUE TITLE
Use Fetch.

### ISSUE THREAD

**Issue by alexmacarthur** [alexmacarthur/wp-vue#7]
Slim down the dependencies by removing Axios and using `fetch` for grabbing post content from the API.

**Comment by ariona** [comment]
@alexmacarthur i am trying to use fetch API in my react project, but couldn't get the response header for getting x-wp-total & x-wp-total-pages since the CORS issue. Did you have figure it out?

**Comment by alexmacarthur** [comment]
@ariona I had some similar troubles, but discovered you can use `response.headers.get('x-wp-total')` to retrieve them. See my commit here: 

https://github.com/alexmacarthur/wp-vue/commit/7442f33237394c816ee1dac90af0c7463d9a10d9#diff-cd5b0dc214837c1a991941f7c98e79a9R28
